# SETTTINGS

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
# DataSet
dataset = "titanic.csv"

# Outliers Switch & Proportion
remove_outliers = False
outlier_proportion = 1.5

# Feature Selection Embedded
rf_feature_embedded = False

# Columns to Drop
columns_to_drop = []

# Target Variable Assignment
target_name = 'Survived'

# Data Types & Conversion
data_types = {0:'int32', 1:'int64', 2:'float32', 3:'float64', 4:'str', 5:'object'}
features_to_convert = {}

# Model Name
pickle_name = "titanic_multi_classify_model"

<hr style='height:10px'>

<br id='basic'>

## BASIC LIBRARIES

* <b>Numpy</b> - Numerical Analysis Library
* <b>Pandas</b> - For Data Load, Exploratory Data Analysis and Data Preprocessing
* <b>Matplotlib</b> - For Charts or Plots
* <b>Seaborn</b> - for Charts or Plots built on top of Matplotlib

In [3]:
# Numpy
import numpy as np

# Pandas
import pandas as pd

# Matplotlib
import matplotlib.pyplot as plt

# Seaborn
import seaborn as sns

from scipy.stats import skew

import statistics as st

In [4]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

<hr style='height:10px'>

<br id='preparation'>

## DATA PREPARATION

In [5]:
df = pd.read_csv('./'+dataset)

## Strip Trail Spacesin Column Names

In [6]:
df.columns = [col.strip() for col in df.columns]

In [7]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

<hr style='height:10px'>

<br id='eda'>

## EXPLORATORY DATA ANALYSIS

<br id='shape'>

#### DataFrame Shape

In [8]:
df.shape   # (rows, columns)

(891, 12)

<br id='head'>

#### First 5 Rows

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<br id='tail'>

#### Last 5 Rows

In [10]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

<br id='freq'>

#### Target Variable - Frequency

In [11]:
df[target_name].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

<br id='dtypes'>

#### DataTypes

In [12]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

<br id='cat'>

#### Categorical Features

In [13]:
cat_features = df.dtypes[df.dtypes == 'object'].index

<br id='catstat'>

#### Summary Statistics of all Categorical Fetures

* We have used Pandas describe method on all the Numerical Features to understand Statistical Information like -
    
        1. Max
        2. Min

In [14]:
# Summarize categorical features
df[cat_features].describe()

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

<br id='num'>

###  Numerical Features

In [15]:
for features in df.dtypes[df.dtypes != 'object'].index:
    print(features)

PassengerId
Survived
Pclass
Age
SibSp
Parch
Fare

<br id='numstat'>

### Summary Statistics of all Numerical Fetures

* We have used Pandas describe method on all the Numerical Features to understand Statistical Information like -
    
        1. Mean
        2. Standard Deviation
        3. Max
        4. Min
        5. 25th Percentile
        6. 50th Percentile
        7. 75th Percentile

In [16]:
num_features = df.dtypes[df.dtypes != 'object'].index

In [17]:
# Summarize numerical features
df[num_features].describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

<br id='cat'>

### List of Categorical Features in DataFrame

In [18]:
df.dtypes[df.dtypes=='object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

<hr style='height:10px'>

<br id='neg'>

### Replace Negative Values with Zero

* Replaced Negative Values as Multinomial Naive Bayes and related Algorithms doesn't accept Negative Values

In [19]:
num = df._get_numeric_data()

num[num < 0] = 0

<br id='unnec'>

### Remove Unnecessary Features

In [20]:
df = df.drop(columns_to_drop, axis=1)

<br id='dropdups'>

### Drop Duplicates

1. Check the Shape before removing duplicates
2. Used Pandas "drop_duplicates" method to remove duplicates
3. Cross checked Shape after removing duplicates to understand how many duplicate rows present in the dataframe
4. We have found 33 duplicate rows in the given sample of around 200K rows
5. Duplicate rows are subject to change as we have taken Sample of 200K rows rather than all to reduce overhead on the server during Training Phase

In [21]:
# Check the Number of Rows before Removing Duplicates
df.shape

(891, 12)

In [22]:
# Call drop_duplicates on DataFrame to remove Duplicates and Assign it back to DataFrame
df = df.drop_duplicates()

In [23]:
# Check the Number of Rows after Removing Duplicates
df.shape

(891, 12)

<br id='inf'>

### Replace "Inf" Values with it's mean value

In [24]:
df = df.replace([np.inf, -np.inf], np.nan)   # replaced "Inf" and "-Inf" with "NaN"

### Remove Unwanted OUTLIERS !!!

### Get Feature and respective outliers count

In [25]:
for feature in df.dtypes[df.dtypes != 'object'].index:
    count = []
    median = np.median(df[feature])
    upper_quartile = np.percentile(df[feature], 75)
    lower_quartile = np.percentile(df[feature], 25)
    iqr = upper_quartile - lower_quartile
    maxim = df[df[feature] <= upper_quartile + outlier_proportion * iqr][feature].max()
    minim = df[df[feature] >= lower_quartile - outlier_proportion * iqr][feature].min()
    for val in df[feature].values:
        if((val > maxim) or (val < minim)):
            count.append(val)
    if(len(count) > 0):
        print(feature, 'has ', str(len(count)), ' outliers. The Outliers are', ' : ', count)
        print('\n')

SibSp has  46  outliers. The Outliers are  :  [np.int64(3), np.int64(4), np.int64(3), np.int64(3), np.int64(4), np.int64(5), np.int64(3), np.int64(4), np.int64(5), np.int64(3), np.int64(3), np.int64(4), np.int64(8), np.int64(4), np.int64(4), np.int64(3), np.int64(8), np.int64(4), np.int64(8), np.int64(3), np.int64(4), np.int64(4), np.int64(4), np.int64(4), np.int64(8), np.int64(3), np.int64(3), np.int64(5), np.int64(3), np.int64(5), np.int64(3), np.int64(4), np.int64(4), np.int64(3), np.int64(3), np.int64(5), np.int64(4), np.int64(3), np.int64(4), np.int64(8), np.int64(4), np.int64(3), np.int64(4), np.int64(8), np.int64(4), np.int64(8)]


Parch has  213  outliers. The Outliers are  :  [np.int64(1), np.int64(2), np.int64(1), np.int64(5), np.int64(1), np.int64(1), np.int64(5), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(3), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(4), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(4), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(3), np.int64(4), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(4), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(5), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(5), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(6), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(3), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(3), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(3), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(5), np.int64(2)]


Fare has  116  outliers. The Outliers are  :  [np.float64(71.2833), np.float64(263.0), np.float64(146.5208), np.float64(82.1708), np.float64(76.7292), np.float64(80.0), np.float64(83.475), np.float64(73.5), np.float64(263.0), np.float64(77.2875), np.float64(247.5208), np.float64(73.5), np.float64(77.2875), np.float64(79.2), np.float64(66.6), np.float64(69.55), np.float64(69.55), np.float64(146.5208), np.float64(69.55), np.float64(113.275), np.float64(76.2917), np.float64(90.0), np.float64(83.475), np.float64(90.0), np.float64(79.2), np.float64(86.5), np.float64(512.3292), np.float64(79.65), np.float64(153.4625), np.float64(135.6333), np.float64(77.9583), np.float64(78.85), np.float64(91.0792), np.float64(151.55), np.float64(247.5208), np.float64(151.55), np.float64(110.8833), np.float64(108.9), np.float64(83.1583), np.float64(262.375), np.float64(164.8667), np.float64(134.5), np.float64(69.55), np.float64(135.6333), np.float64(153.4625), np.float64(133.65), np.float64(66.6), np.float64(134.5), np.float64(263.0), np.float64(75.25), np.float64(69.3), np.float64(135.6333), np.float64(82.1708), np.float64(211.5), np.float64(227.525), np.float64(73.5), np.float64(120.0), np.float64(113.275), np.float64(90.0), np.float64(120.0), np.float64(263.0), np.float64(81.8583), np.float64(89.1042), np.float64(91.0792), np.float64(90.0), np.float64(78.2667), np.float64(151.55), np.float64(86.5), np.float64(108.9), np.float64(93.5), np.float64(221.7792), np.float64(106.425), np.float64(71.0), np.float64(106.425), np.float64(110.8833), np.float64(227.525), np.float64(79.65), np.float64(110.8833), np.float64(79.65), np.float64(79.2), np.float64(78.2667), np.float64(153.4625), np.float64(77.9583), np.float64(69.3), np.float64(76.7292), np.float64(73.5), np.float64(113.275), np.float64(133.65), np.float64(73.5), np.float64(512.3292), np.float64(76.7292), np.float64(211.3375), np.float64(110.8833), np.float64(227.525), np.float64(151.55), np.float64(227.525), np.float64(211.3375), np.float64(512.3292), np.float64(78.85), np.float64(262.375), np.float64(71.0), np.float64(86.5), np.float64(120.0), np.float64(77.9583), np.float64(211.3375), np.float64(79.2), np.float64(69.55), np.float64(120.0), np.float64(93.5), np.float64(80.0), np.float64(83.1583), np.float64(69.55), np.float64(89.1042), np.float64(164.8667), np.float64(69.55), np.float64(83.1583)]

### Remove all the Outliers

In [26]:
if remove_outliers:
    for feature in df.dtypes[df.dtypes!='object'].index:
        count = []
        median = np.median(df[feature])
        upper_quartile = np.percentile(df[feature], 75)
        lower_quartile = np.percentile(df[feature], 25)
        iqr = upper_quartile - lower_quartile
        maxim = df[df[feature] <= upper_quartile + outlier_proportion * iqr][feature].max()
        minim = df[df[feature] >= lower_quartile - outlier_proportion * iqr][feature].min()
        for val in df[feature].values:
            if((val > maxim) or (val < minim)):
                df[feature] = df[df[feature] != val][feature]

### Check the Outliers again

In [27]:
for feature in df.dtypes[df.dtypes!='object'].index:
    count = []
    median = np.median(df[feature])
    upper_quartile = np.percentile(df[feature], 75)
    lower_quartile = np.percentile(df[feature], 25)
    iqr = upper_quartile - lower_quartile
    maxim = df[df[feature] <= upper_quartile + outlier_proportion * iqr][feature].max()
    minim = df[df[feature] >= lower_quartile - outlier_proportion * iqr][feature].min()
    for val in df[feature].values:
        if((val > maxim) or (val < minim)):
            count.append(val)
    if(len(count) > 0):
        print(feature, 'has ', str(len(count)), ' outliers. The Outliers are', ' : ', count)
        print('\n')

SibSp has  46  outliers. The Outliers are  :  [np.int64(3), np.int64(4), np.int64(3), np.int64(3), np.int64(4), np.int64(5), np.int64(3), np.int64(4), np.int64(5), np.int64(3), np.int64(3), np.int64(4), np.int64(8), np.int64(4), np.int64(4), np.int64(3), np.int64(8), np.int64(4), np.int64(8), np.int64(3), np.int64(4), np.int64(4), np.int64(4), np.int64(4), np.int64(8), np.int64(3), np.int64(3), np.int64(5), np.int64(3), np.int64(5), np.int64(3), np.int64(4), np.int64(4), np.int64(3), np.int64(3), np.int64(5), np.int64(4), np.int64(3), np.int64(4), np.int64(8), np.int64(4), np.int64(3), np.int64(4), np.int64(8), np.int64(4), np.int64(8)]


Parch has  213  outliers. The Outliers are  :  [np.int64(1), np.int64(2), np.int64(1), np.int64(5), np.int64(1), np.int64(1), np.int64(5), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(3), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(4), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(4), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(3), np.int64(4), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(4), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(5), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(5), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(6), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(3), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(3), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(3), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(5), np.int64(2)]


Fare has  116  outliers. The Outliers are  :  [np.float64(71.2833), np.float64(263.0), np.float64(146.5208), np.float64(82.1708), np.float64(76.7292), np.float64(80.0), np.float64(83.475), np.float64(73.5), np.float64(263.0), np.float64(77.2875), np.float64(247.5208), np.float64(73.5), np.float64(77.2875), np.float64(79.2), np.float64(66.6), np.float64(69.55), np.float64(69.55), np.float64(146.5208), np.float64(69.55), np.float64(113.275), np.float64(76.2917), np.float64(90.0), np.float64(83.475), np.float64(90.0), np.float64(79.2), np.float64(86.5), np.float64(512.3292), np.float64(79.65), np.float64(153.4625), np.float64(135.6333), np.float64(77.9583), np.float64(78.85), np.float64(91.0792), np.float64(151.55), np.float64(247.5208), np.float64(151.55), np.float64(110.8833), np.float64(108.9), np.float64(83.1583), np.float64(262.375), np.float64(164.8667), np.float64(134.5), np.float64(69.55), np.float64(135.6333), np.float64(153.4625), np.float64(133.65), np.float64(66.6), np.float64(134.5), np.float64(263.0), np.float64(75.25), np.float64(69.3), np.float64(135.6333), np.float64(82.1708), np.float64(211.5), np.float64(227.525), np.float64(73.5), np.float64(120.0), np.float64(113.275), np.float64(90.0), np.float64(120.0), np.float64(263.0), np.float64(81.8583), np.float64(89.1042), np.float64(91.0792), np.float64(90.0), np.float64(78.2667), np.float64(151.55), np.float64(86.5), np.float64(108.9), np.float64(93.5), np.float64(221.7792), np.float64(106.425), np.float64(71.0), np.float64(106.425), np.float64(110.8833), np.float64(227.525), np.float64(79.65), np.float64(110.8833), np.float64(79.65), np.float64(79.2), np.float64(78.2667), np.float64(153.4625), np.float64(77.9583), np.float64(69.3), np.float64(76.7292), np.float64(73.5), np.float64(113.275), np.float64(133.65), np.float64(73.5), np.float64(512.3292), np.float64(76.7292), np.float64(211.3375), np.float64(110.8833), np.float64(227.525), np.float64(151.55), np.float64(227.525), np.float64(211.3375), np.float64(512.3292), np.float64(78.85), np.float64(262.375), np.float64(71.0), np.float64(86.5), np.float64(120.0), np.float64(77.9583), np.float64(211.3375), np.float64(79.2), np.float64(69.55), np.float64(120.0), np.float64(93.5), np.float64(80.0), np.float64(83.1583), np.float64(69.55), np.float64(89.1042), np.float64(164.8667), np.float64(69.55), np.float64(83.1583)]

<hr style='height:4px'>

### Remove NULLs

In [28]:
# Check Columns that has NULLs
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### NULLs

#### Fill all the NULLs in Numerical Features with fill (when Values in Numerical Features are Repetetive in Nature)

In [30]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [31]:
for feature in df.isnull().sum()[df[df.dtypes.index].isnull().sum() > 0].index:
    if (np.dtype(df[feature]) == np.dtype('int64') or np.dtype(df[feature]) == np.dtype('float64')):
        if skew(df[feature]) <= 5.0:
            df[feature] = df[feature].mean()
        elif skew(df[feature]) >= 5.0 and skew(df[feature]) <= 10.0:
            df[feature] = df[feature].ffill()
            df[feature] = df[feature].bfill()
        else:
            df[feature] = df[feature].fillna(0)
    else:
        if len(df[feature].unique()) / len(df[feature]) <= 5.0:
            df[feature] = df[feature].fillna(st.mode(df[df[feature].notnull()][feature]))
        elif len(df[feature].unique()) / len(df[feature]) >= 5.0 and len(df[feature].unique()) / len(df[feature]) <= 10.0:
            df[feature] = df[feature].ffill()
            df[feature] = df[feature].bfill()
        else:
            df[feature] = df[feature].fillna('Missing')

#### Check NULLs again

In [32]:
# Check Columns that has NULLs After dealing with NULL values in the respective Features
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## Convert Data Types of Features

In [33]:
if len(features_to_convert) != 0:
    for col, data_type in features_to_convert.items():
        df[col] = df[col].astype(data_type)

### Label Encoding

In [34]:
final_dict = {}

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
for feature in df.dtypes[df.dtypes != 'object'].index:
    final_dict[feature] = [df[feature].dtype, min(df[feature]), max(df[feature]), np.mean(df[feature])]

In [38]:
for feature in df.dtypes[df.dtypes=='object'].index:
    label_encoder  = LabelEncoder()
    feature_unique_values = list(df[feature].unique())
    df[feature] = label_encoder.fit_transform(df[feature])
    final_dict[feature] = ['object', feature_unique_values, label_encoder]

In [39]:
final_dict['target'] = target_name

<hr style='height:10px'>

<br id='model'>

## Model Preparation & Training

<br id='targetinput'>

### Seperate objects for TARGET & INPUT features

In [40]:
# Separate object for target feature
y = df[target_name]

# Separate Object for Input Features
X = df.drop(target_name, axis=1)

<br id='split'>

### Train Test Split

* We have used train_test_split from sklearn (sklearn.model_selection)
* We have choosen Test Size as 30%. So, the Train size is going to be 70%
* X_train - Train set of Independent Variables
* X_test -  Test set of Independent Variables
* y_train - Train set of Dependent/Target Variable
* y_test  - Test set of Dependent/Target Variable

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
# Split X and y into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

<hr style='height:10px'>

<br id='features'>

## Feature Selection
    Filter Methods
         Basic
             Constant Features
             Quasi-Constant Features
             Duplicated Features
         Correlation

In [43]:
X_train.shape, X_test.shape

((623, 11), (268, 11))

In [44]:
# I keep a copy of the dataset with all the variables
# to measure the performance of machine learning models
# at the end of the notebook

X_train_original = X_train.copy()
X_test_original = X_test.copy()

In [45]:
X_train_original.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
28,29,3,605,0,0.0,0,0,283,7.8792,145,1
270,271,1,125,1,0.0,0,0,47,31.0000,145,2
744,745,3,788,1,31.0,0,0,662,7.9250,145,2
73,74,3,161,1,26.0,1,0,204,14.4542,145,0
423,424,3,198,0,28.0,1,1,331,14.4000,145,2

### Remove constant & quasi-constant features

* Import VarianceThreshold (sklearn.feature_selection)
* Assign the threshold 0.01, which indicates 1% variance i.e., 99% constant
* Get all the features that are not Constant (100% Constant) or Quasi-Constant (99% or more Constant)
* Store all the collected Non-Constant features in "feature_to_keep" variable (List)
* Select only those features that are in "feature_to_keep" variable in X_train and X_test

In [46]:
from sklearn.feature_selection import VarianceThreshold

In [47]:
# remove quasi-constant features
sel = VarianceThreshold(
    threshold=0.01)  # 0.01 indicates 99% of observations approximately

sel.fit(X_train)  # fit finds the features with low variance

sum(sel.get_support()) # how many not quasi-constant?

np.int64(11)

In [48]:
features_to_keep = X_train.columns[sel.get_support()]

In [49]:
features_to_keep

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [50]:
# we can then remove the features like this
X_train = sel.transform(X_train)
X_test = sel.transform(X_test)

X_train.shape, X_test.shape

((623, 11), (268, 11))

In [51]:
# sklearn transformations lead to numpy arrays
# here I transform the arrays back to dataframes
# please be mindful of getting the columns assigned
# correctly

X_train= pd.DataFrame(X_train)
X_train.columns = features_to_keep

X_test= pd.DataFrame(X_test)
X_test.columns = features_to_keep

### Remove duplicated features

* Create a loop such that every Features maps with all other features available
* Check every combination of features equal or not
* If it is equal/duplicate, add to list "duplicated_feat"
* Remove duplicated features using drop method

In [52]:
# check for duplicated features in the training set
duplicated_feat = []
for i in range(0, len(X_train.columns)):
    col_1 = X_train.columns[i]

    for col_2 in X_train.columns[i + 1:]:
        if X_train[col_1].equals(X_train[col_2]):
            duplicated_feat.append(col_2)

len(duplicated_feat)

0

In [53]:
# remove duplicated features
X_train.drop(labels=duplicated_feat, axis=1, inplace=True)
X_test.drop(labels=duplicated_feat, axis=1, inplace=True)

X_train.shape, X_test.shape

((623, 11), (268, 11))

In [54]:
X_train_basic = X_train.copy()
X_test_basic = X_test.copy()

In [55]:
X_train.shape

(623, 11)

### Remove correlated features

* Get Correlation Mapping between all the Features using corr()
* Loop all the Features such that every Feature maps with other Features available
* Check Correlation between every combination of features greater than given "threshold"
* Store all the Correlated features greater than threshold in a set
* Return the set
* Drop the Correlated features from X_train and X_test (Input/Independent Variables)

In [56]:
# find and remove correlated features
def correlation(dataset, threshold):
    col_corr = set()  # Set of all the names of correlated columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold: # we are interested in absolute coeff value
                colname = corr_matrix.columns[i]  # getting the name of column
                col_corr.add(colname)
    return col_corr

In [57]:
corr_features = correlation(X_train, 0.8)
print('correlated features: ', len(set(corr_features)))

correlated features:  0

In [58]:
X_train.drop(labels=corr_features, axis=1, inplace=True)
X_test.drop(labels=corr_features, axis=1, inplace=True)

X_train.shape, X_test.shape

((623, 11), (268, 11))

In [59]:
X_train_corr = X_train.copy()
X_test_corr = X_test.copy()

In [60]:
X_train.shape

(623, 11)

### Select features by random forests derived importance

In [61]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

In [62]:
sel_ = SelectFromModel(RandomForestClassifier(n_estimators=400))
sel_.fit(X_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(n_estimators=400))

In [63]:
X_train_rf = pd.DataFrame(sel_.transform(X_train))
X_test_rf = pd.DataFrame(sel_.transform(X_test))

In [64]:
# add the columns name
X_train_rf.columns = X_train.columns[(sel_.get_support())]
X_test_rf.columns = X_train.columns[(sel_.get_support())]

In [65]:
X_train_rf.shape, X_test_rf.shape

((623, 6), (268, 6))

In [66]:
rf_features = X_train_rf.columns

In [67]:
final_dict['rf_features'] = rf_features

In [68]:
if rf_feature_embedded:
    X_train = X_train_rf
    X_test = X_test_rf

<hr style='height:10px'>

<br id='advlibraries'>

## CLASSIFICATION ALGORITHMS

* Random Forest Classifier
* Gradient Boosting Classifier
* Logistic Regression
* Decision Tree Classifier
* K-Neighbors Classifier
* Multinomial Naive Bayes
* Gaussian Naive Bayes
* Benouli Naive Bayes

#### Random Forest Classifier

In [69]:
from sklearn.ensemble import RandomForestClassifier

#### Gradient Boosting Classifier

In [70]:
from sklearn.ensemble import GradientBoostingClassifier

#### Logistic Regression Classifier

In [71]:
from sklearn.linear_model import LogisticRegression

#### Decision Tree Classifier

In [72]:
from sklearn.tree import DecisionTreeClassifier

#### K-Nearest Neighbors Classifier

In [73]:
from sklearn.neighbors import KNeighborsClassifier

#### Naive Bayes Classifiers

In [74]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB

In [75]:
from sklearn.pipeline import make_pipeline

#### Standard Scaler

In [76]:
from sklearn.preprocessing import StandardScaler

### Pipeline

In [77]:
pipeline_dict = {'lgl2': make_pipeline(StandardScaler(), LogisticRegression(penalty='l2', random_state=123)),
                 'rfc': make_pipeline(StandardScaler(), RandomForestClassifier(random_state=123)),
                 'gbc': make_pipeline(StandardScaler(), GradientBoostingClassifier(random_state=123)),
                 'dtc': DecisionTreeClassifier(random_state=123),
                 'mnb': MultinomialNB(),
                 'gnb': GaussianNB(),
                 'bnb': BernoulliNB()
                }

<hr style='height:10px'>

<br id='hyper'>

## Hyperparameters

#### Logistic Regression Hyperparameters

* logisticregression__C -->  parameter is like L1 Penalty. It helps in reducing noise. Less the C values, more the Penalty.

In [78]:
# Logistic Regression hyperparameters
lgl2_hyperparameters = { 'logisticregression__C': np.linspace(1e-3, 1e3, 10)}

#### Random Forest Hyperparameters

* randomforestclassifier__n_estimators --> Maximum Number of Trees
* randomforestclassifier__max_features --> Maximum number of features to be selected during Model training phase

In [79]:
# Random Forest hyperparameters
rfc_hyperparameters = { 'randomforestclassifier__n_estimators': [100, 200],
                         'randomforestclassifier__max_features': ['auto', 'sqrt', 0.33]
                     }

#### Gradient Boosting Hyperparameters

* gradientboostingclassifier__n_estimators  --> Maximum number of Trees
* gradientboostingclassifier__learning_rate --> Learning rate is a tuning parameter in an optimization algorithm that determines the step size at each iteration while moving toward a minimum of a loss function.
* gradientboostingclassifier__max_depth     --> Depth of a Decision Tree

In [80]:
# Boosted Tree hyperparameters
gbc_hyperparameters = {'gradientboostingclassifier__n_estimators': [100, 200],
                    'gradientboostingclassifier__learning_rate': [0.05, 0.1, 0.2],
                     'gradientboostingclassifier__max_depth': [1, 3, 5]
                     }

#### Decision Tree Hyperparameters

* criterion --> Classification Purity (Gini, Entropy)
* splitter  --> The strategy used to choose the split at each node. Supported strategies are “best” to choose the best split and “random” to choose the best random split.
* min_samples_leaf --> The minimum number of samples required to be at a leaf node
* min_samples_split -->  The minimum number of samples required to split an internal node
* max_depth --> Depth of a Decision Tree
* random_state --> Value to be set to distribute same set of randomized rows to all the algorithms

In [81]:
# Decision Tree Classifier hyperparameters
dtc_hyperparameters = {'criterion': ['gini','entropy'],
                      'splitter': ['best', 'random'],
                      'min_samples_leaf': [1,3,5,7, 10],
                      'min_samples_split': [2,5,7,10,12],
                      'max_depth': [2,4,6,8,10,None],
                      'random_state': [0]
                      }

#### K-Nearest Neighbors Hyperparameters

* p           -->  Experiment Error Proportion
* n_neighbors --> Number of neighbors to use by default for kneighbors queries.

##### metric (KNN)

###### City Block

![city_block_distance.png](attachment:city_block_distance.png)

###### Euclidean Distance

<font size=4><center>sqrt(sum((x - y)^2))<center></font>

In [82]:
# K Nearest Neighbors hyperparameters
knn_hyperparameters = {'p': [1, 2, 3, 4, 5],
                      'n_neighbors': list(range(1,30)),
                      'metric': ["euclidean", "cityblock"]
                      }

#### Multinomial Naive Bayes Hyperparameters

* alpha     --> Additive (Laplace/Lidstone) smoothing parameter (0 for no smoothing).

* fit_prior --> Whether to learn class prior probabilities or not. If false, a uniform prior will be used.

In [83]:
# Multinomial Naive Bayes Hyperparameters
mnb_hyperparameters = { 'alpha': np.linspace(0.5, 1.5, 6),
                       'fit_prior': [True, False]
                        }

#### Gaussian Naive Bayes Hyperparameters

* fit_prior --> Whether to learn class prior probabilities or not. If false, a uniform prior will be used.

#### Binomial Naive Bayes Hyperparameters

* alpha     --> Additive (Laplace/Lidstone) smoothing parameter (0 for no smoothing).

* fit_prior --> Whether to learn class prior probabilities or not. If false, a uniform prior will be used.

In [84]:
bnb_hyperpaeters = {'alpha': np.linspace(0.5, 1.5, 6),
                       'fit_prior': [True, False]
                   }

#### Hyperparameters Dictionary

* Hyperparameter Dictionary going to be passed as Parameter to GridSearchCV
* It simplifies in applying hyperparameters to all the respective algorithms in GridSearchCV

In [85]:
# Create hyperparameters dictionary
hyperparameters = {
           'lgl2': lgl2_hyperparameters,
           'rfc': rfc_hyperparameters,
           'gbc': gbc_hyperparameters,
           'dtc': dtc_hyperparameters,
           'mnb': mnb_hyperparameters,
           'bnb': bnb_hyperpaeters,
           'gnb': {}
          }

<hr style='height:10px'>

<br id='fit'>

### Training / Fitting

* Import GridSearchCV for Cross Validation
* Create a dictionary to store fitted models - fitted_models
* Loop pipeline_dict to get Pipeline and Name of Algorithms to feed GridSearchCV
* Fit the Model with X_train and y_train
* Store the Model in fitted_models dictionary
* Print once the model been fitted and stored in fitted_models dictionary
* Check the availability of all the Cross-Validation Objects
* Check All the Algorithms are fitted

In [86]:
from sklearn.model_selection import GridSearchCV

In [87]:
fitted_models = {}

for name, pipeline in pipeline_dict.items():

    model = GridSearchCV(pipeline, hyperparameters[name], cv=10, n_jobs=-1)

    model.fit(X_train, y_train)

    fitted_models[name] = model

    print(name, 'has been fitted.')

lgl2 has been fitted.
rfc has been fitted.
gbc has been fitted.
dtc has been fitted.
mnb has been fitted.
gnb has been fitted.
bnb has been fitted.

<hr style='height:10px'>

<br id='eval'>

## EVALUATE MODELS

### Predict Values by Best Score & Accuracy Score of Fitted Models

In [88]:
pred = {}
for name, model in fitted_models.items():
    pred[name] = fitted_models[name].predict(X_test)

#### Display first 10 predictions

In [89]:
for key, val in pred.items():
    print('First 10 {} predicted values are {}'.format(key, pred[key][:10]))

First 10 lgl2 predicted values are [1 0 0 1 0 0 0 1 0 0]
First 10 rfc predicted values are [1 0 0 1 1 0 1 0 0 0]
First 10 gbc predicted values are [1 0 0 1 1 0 1 0 0 0]
First 10 dtc predicted values are [1 0 0 1 1 0 1 1 0 0]
First 10 mnb predicted values are [1 0 0 1 1 0 1 0 0 0]
First 10 gnb predicted values are [1 0 0 1 1 0 0 1 0 0]
First 10 bnb predicted values are [1 0 0 1 0 1 0 1 0 0]

### Accuracy Score

In [90]:
from sklearn.metrics import accuracy_score

In [91]:
final_dict['model_score'] = []
i = 0
for key, val in pred.items():
    acc_score = accuracy_score(y_test, pred[key])
    print('{} accuracy score is {}'.format(key, acc_score))
    final_dict['model_score'].append((i, key, acc_score))
    i += 1

lgl2 accuracy score is 0.8246268656716418
rfc accuracy score is 0.8656716417910447
gbc accuracy score is 0.832089552238806
dtc accuracy score is 0.8097014925373134
mnb accuracy score is 0.664179104477612
gnb accuracy score is 0.7574626865671642
bnb accuracy score is 0.8097014925373134

### Confusion Matrix

In [92]:
# Import confusion_matrix
from sklearn.metrics import confusion_matrix

In [93]:
# Display confusion matrix for y_test and pred
for key, val in pred.items():
    print ('{} confusion matrix is \n{}\n'.format(key, confusion_matrix(y_test, pred[key])))

lgl2 confusion matrix is
[[148  18]
 [ 29  73]]

rfc confusion matrix is
[[152  14]
 [ 22  80]]

gbc confusion matrix is
[[150  16]
 [ 29  73]]

dtc confusion matrix is
[[147  19]
 [ 32  70]]

mnb confusion matrix is
[[123  43]
 [ 47  55]]

gnb confusion matrix is
[[144  22]
 [ 43  59]]

bnb confusion matrix is
[[145  21]
 [ 30  72]]

## Classification Report

In [94]:
from sklearn.metrics import classification_report

In [95]:
for key, val in pred.items():
    print('\n{} classification report is: \n {}'.format(key, classification_report(y_test, pred[key])))
    print('---------------------------------------------------------------------------------------------')

lgl2 classification report is:
               precision    recall  f1-score   support

           0       0.84      0.89      0.86       166
           1       0.80      0.72      0.76       102

    accuracy                           0.82       268
   macro avg       0.82      0.80      0.81       268
weighted avg       0.82      0.82      0.82       268

---------------------------------------------------------------------------------------------

rfc classification report is:
               precision    recall  f1-score   support

           0       0.87      0.92      0.89       166
           1       0.85      0.78      0.82       102

    accuracy                           0.87       268
   macro avg       0.86      0.85      0.86       268
weighted avg       0.87      0.87      0.86       268

---------------------------------------------------------------------------------------------

gbc classification report is:
               precision    recall  f1-score   support

           0       0.84      0.90      0.87       166
           1       0.82      0.72      0.76       102

    accuracy                           0.83       268
   macro avg       0.83      0.81      0.82       268
weighted avg       0.83      0.83      0.83       268

---------------------------------------------------------------------------------------------

dtc classification report is:
               precision    recall  f1-score   support

           0       0.82      0.89      0.85       166
           1       0.79      0.69      0.73       102

    accuracy                           0.81       268
   macro avg       0.80      0.79      0.79       268
weighted avg       0.81      0.81      0.81       268

---------------------------------------------------------------------------------------------

mnb classification report is:
               precision    recall  f1-score   support

           0       0.72      0.74      0.73       166
           1       0.56      0.54      0.55       102

    accuracy                           0.66       268
   macro avg       0.64      0.64      0.64       268
weighted avg       0.66      0.66      0.66       268

---------------------------------------------------------------------------------------------

gnb classification report is:
               precision    recall  f1-score   support

           0       0.77      0.87      0.82       166
           1       0.73      0.58      0.64       102

    accuracy                           0.76       268
   macro avg       0.75      0.72      0.73       268
weighted avg       0.75      0.76      0.75       268

---------------------------------------------------------------------------------------------

bnb classification report is:
               precision    recall  f1-score   support

           0       0.83      0.87      0.85       166
           1       0.77      0.71      0.74       102

    accuracy                           0.81       268
   macro avg       0.80      0.79      0.79       268
weighted avg       0.81      0.81      0.81       268

---------------------------------------------------------------------------------------------

<hr style='height:10px'>

<br id='finalmodel'>

## Best Estimator & Tuned Parameters

In [96]:
best_model = final_dict['model_score'][max(final_dict['model_score'], key = lambda i : i[2])[0]][1]

### Save the Model

In [97]:
import pickle

In [98]:
final_dict['model'] = fitted_models[best_model].best_estimator_

In [100]:
with open('./'+pickle_name + '.pkl', 'wb') as f:
    pickle.dump(final_dict, f)

In [ ]:
fitted_models[best_model].best_estimator_

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('gradientboostingclassifier',
                 GradientBoostingClassifier(max_depth=5, n_estimators=200,
                                            random_state=123))])

<hr style='height:10px'>